detectors:
  palmX:
    num_frames: 40
    threshold: 30.0
  palmY:
    num_frames: 40
    threshold: 30.0

time:
  fps: 50
  skip-seconds: 1

# thresholds: max number of events per minute for this level
motion:
  move-vertical:
    low: 1
    medium: 2
  counter-move-horizontal:
    low: 1
    medium: 2
